- hosts: configmeta-sit-node1
  remote_user: wtadmin
  tasks:
     - name: mkdir metaprovider
       file: dest=/data01/install owner=wtadmin  group=wtadmin  mode=755 state=directory
     - name: Copy meta-provider.sh
       copy: src=/root/.jenkins/workspace/config-meta/meta-provider.sh dest=/data01/install owner=wtadmin group=wtamdin  mode=755
     - name: romove metaprovider
       file: dest=/data01/install/ch5_2_2-0.0.1-SNAPSHOT.jar state=absent
     - name: copy metaprovider
       file: src=/home/wtadmin/.jenkins/workspace/config-meta/targetch5_2_2-0.0.1-SNAPSHOT.jar dest=/data01/install/ch5_2_2-0.0.1-SNAPSHOT.jar owner=wtadmin group=wtamdin mode=755
     - name: stop metaprovider port 9091
       shell: cd /data01/install/;./meta-provider.sh stop ch5_2_2-0.0.1-SNAPSHOT.jar.jar 9091 &  
       async: 10
     - name: start metaprovider port 9091
       shell: cd /data01/install/;./meta-provider.sh start ch5_2_2-0.0.1-SNAPSHOT.jar 9091 &  
       async: 10
       poll: 0