- hosts: configmeta-sit-node1
  tasks:
     - name: mkdir metaprovider
       file: dest=/data01/install state=directory
     - name: Copy meta-provider.sh
       copy: src=/root/.jenkins/workspace/config-meta/meta-provider.sh dest=/data01/install  owner=root group=root  mode=755
     - name: copy metaprovider
       copy: src=/root/.jenkins/workspace/config-meta/target/ch5_2_2-0.0.1-SNAPSHOT.jar dest=/data01/install/ owner=root group=root  mode=755
     - name: stop metaprovider port 9091
       shell: cd /data01/install/;./meta-provider.sh stop ch5_2_2-0.0.1-SNAPSHOT.jar 9091 &  
       async: 10
     - name: start metaprovider port 9091
       shell: cd /data01/install/;nohup ./meta-provider.sh start ch5_2_2-0.0.1-SNAPSHOT.jar 9091 &  
       async: 10
       poll: 0
